### ISSUE TITLE
New Custom Derive

### ISSUE THREAD

**Issue by KodrAus** [elastic-rs/elastic-types#55]
This is an overarching issue to rework the custom derive macros for `types` and `dates` which includes the following:

- [ ] Move `types` functionality into a new crate: `elastic_types_codegen` https://github.com/elastic-rs/elastic-types/issues/54
- [ ] Create a new crate `elastic_derive` that supports codegen using the alternative crate root https://github.com/elastic-rs/elastic-types/issues/54
- [ ] Move `date` functionality into `elastic_types_codegen` https://github.com/elastic-rs/elastic-types/issues/38
- [ ] Create new `date` parser as a custom derive that only supports Elasticsearch formats https://github.com/elastic-rs/elastic-types/issues/8

**Comment by KodrAus** [comment]
Alrighty, I'm going to start working on this now.
